name: flutter_page_transition
description: A rich, convenient, easy-to-use flutter page transition package.
version: 0.1.6
homepage: https://github.com/handoing/flutter_page_transition

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
